### ISSUE TITLE
Pings are pretty hard to notice

### ISSUE THREAD

**Issue by Seon82** [pxlsspace/Pxls#383]
First, thanks for this great project!
I've been running in a issue for some time though: pings in chat are extremely discrete, which makes them pretty hard to notice, especially if you're just idly placing. Perhaps a pop-up window could show up after several unread pings? You could make it an option (enabled by default) to avoid abuse.

**Comment by netux** [comment]
Do you still consider pings hard to notice even with the ping sound enabled? (open chat -> ⚙ on the top right)
![image](https://user-images.githubusercontent.com/6181929/85862682-7d1a2980-b798-11ea-9586-97992809d69d.png)
The setting was made off by default to avoid scaring people who didn't know about chat.

**Comment by Seon82** [comment]
No, I think the sound makes them very easy to notice if you're in front of your pc when you get pinged. 
Though as you mentioned, it might be pretty confusing and frustrating to users who've never noticed the chat if it the sound ever gets enabled by default.

**Comment by cp-codes2** [comment]
Personally I don't like the noise and always have it off. which is where the popups come in for online users. As for offline users that's where more noticeable ping counters and such come in. ( which is what I described earlier)
also I feel like most users dont know they can see missed pings by clicking the @ button. I may see if I can change that to glow or something so it is not ignored

**Comment by spark1313** [comment]
It looks like the audible aspect of notifications has been covered since and the scope of this issue can be refined to a feature request for supporting the option of enabling a pop-up window along with the ping or after several missed pings which could potentially utilize the "new report" dropdown for ping messages.

@FlyingSixtySix please rename to "Add Ping Popups Support" or something similar.
