### ISSUE TITLE
Pixel Authentication Rework

### ISSUE THREAD

**Issue by spark1313** [pxlsspace/Pxls#481]
The previous pixel authentication utilized by pxlsfiddle is no longer available and a temporary authentication stopgap is in place. Thus, player pixel lookups are no longer available unless the user has already authenticated in the past.

> The original - janky but brilliant ;) - authentication method using pxls.space's pixel lookups is no longer available.
> While the pxls devs work toward a more appropriate authentication method, please see the temporary pxlsFiddle authentication page instead;

More info via:
https://pxlsfiddle.com/pxlsauth/

**Comment by Undoundoundo** [comment]
This is essentially DUPLICATE #482 or WONTFIX. The issue is not with pxls, but with pxlsFiddle / the rules;

- Only logged in users can look up pixels - fiddle never used an authenticated instance to get those lookups.
- Automated lookups are also against the rules; which is exactly what pxlsFiddle did. Yes, it was user-initiated, but still a mostly automated process.

The OAuth work is what should be replacing the 'janky but brilliant' method.

In the mean time, users _can_ request manual authentication from CtrlZ / Zoda / r_Stargate for past pixel lookups.

( which itself should be an issue / eventual PR; the less reliant things are on fiddle, the better )

**Comment by spark1313** [comment]
Good point, #482 is a Blocker for restoring functionality of the feature described here. Closed with reference in $482.
