### ISSUE TITLE
Cannot find placemap.dat

### ISSUE THREAD

**Issue by CColdFox** [pxlsspace/Pxls#582]
Hello, I have a problem when running pxls.jar with `java -jar pxls.jar`, here's the error in the command prompt:
https://pastebin.com/yuVjwz9k

Here's the app.log file:
`2022-04-06 12:09:35,381	Cannot find placemap.dat in working directory, assuming transparent pixels are unplaceable`

Can someone help me?
Thanks!

**Comment by FlyingSixtySix** [comment]
Hi! This is expected behavior - when the site is run without a `placemap.dat` in the configured `storage` directory, it will assume that transparent pixels (byte value `255` in the `default_board.dat`) are unplaceable. You can generate a `placemap.dat` when generating a `default_board.dat` from an image, with the script `extras/convert/img2board.py` (in a Python 3.8+ environment with the `pillow` package installed). Usage of that script is `img2board.py CANVAS PLACEMAP` where the `CANVAS` is a 32-bit PNG using palette colors and `PLACEMAP` is a 32-bit PNG with placeable pixels being opaque with the rest being transparent. For example:

<img src="https://files.f66.dev/uploads/SampleCube.png"> <img src="https://files.f66.dev/uploads/SampleCubePlacemap.png">

The left image is what people will see on the board (generated in `default_board.dat`) and the right image is where they can place on (generated in `placemap.dat`).

Do note that the script is outdated and you *will* need to input a hex array of the palette when prompted. If you're using the default palette, copy and paste this:

`["#000000","#222222","#555555","#888888","#CDCDCD","#FFFFFF","#FFD5BC","#FFB783","#B66D3D","#77431F","#FC7510","#FCA80E","#FDE817","#FFF491","#BEFF40","#70DD13","#31A117","#0B5F35","#277E6C","#32B69F","#88FFF3","#24B5FE","#125CC7","#262960","#8B2FA8","#D24CE9","#FF59EF","#FFA9D9","#FF6474","#F02523","#B11206","#740C00"]`

Thanks!
