### ISSUE TITLE
Discord Auth - You're doing that too much. Try again in X seconds.

### ISSUE THREAD

**Issue by loohney** [pxlsspace/Pxls#585]
I've successfully build and started the jar. Everything seems to be working fine, however when using Discord Auth, it seems that there's a rate limit active (?). Sometimes, it shows a new user an error message when getting redirected from the Discord Auth to my host saying:

"You're doing that too much. Try again in X seconds."

Any ideas?

**Comment by loohney** [comment]
There seems to be some sort of limits in the config (https://github.com/pxlsspace/Pxls/blob/master/resources/reference.conf) - however, how is the Discord Auth one mentioned above triggered?

**Comment by zulujive** [comment]
You can update this limit in the pxls.config file (that one reference.config file that you renamed earlier in /resources). Tbh, the rate limit is a bit out of whack and I wish they made it a little more forgiving.

**Comment by BlankParenthesis** [comment]
> however, how is the Discord Auth one mentioned above triggered?

Here is the code which accesses the mentioned config option: [UndertowServer.java:63](https://github.com/pxlsspace/Pxls/blob/e509ecf1710e0233d2626830e277a500fd7e0088/src/main/java/space/pxls/server/UndertowServer.java#L63)

This simply limits the number of requests that can be made to `/auth` in a given timeframe. The default limits  (3 every 10 minutes) are probably slightly too conservative, I might look into changing them.

**The most common cause of hitting ratelimits like this is usually not because of this however**: the ratelimit is guarded by the user's IP address. Since Pxls is intended to be run in a reverse-proxy environment, this can lead to an insidious misconfiguration where the IP address of all connections appears to be the local loopback address (typically `0.0.0.0`).

To resolve this, there are a couple of things that should be done: first, you should pass the user's real IP from the reverse-proxy to the server. if you are using NGINX adding this to the directive for your proxy should work:

```conf
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

And if you're behind some other service such as Cloudflare, make sure to forward the appropriate headers from there. You can technically pass this via any header you choose, as the next step is to tell Pxls which header to use. The proxy config option lets you specify a headers array with the headers to be searched for real IP addresses. For the one above:

```conf
proxy {
    localhosts: [...]
    headers: ["X-Forwarded-For"]
}
```

You should be able to verify that this is working by making sure your users have unique IPs.
