### ISSUE TITLE
Editing Pebble Templates?

### ISSUE THREAD

**Issue by zulujive** [pxlsspace/Pxls#641]
Every time I edit /resources/public/pebble_templates/info.html the site breaks and I just get a white screen when the page loads. Am I editing the wrong thing?

**Comment by BlankParenthesis** [comment]
If you want to use a custom index and faq, copying the files and setting the config options to the location of the copies is probably what you want to do.

Errors caused while editing these files is likely due to localization issues: if you change a string then the localizer expects to be able to translate it. The process for compiling the new localizations is still mostly correct in the description for #475. One notable nicety is that there's now a script ([update-localizations.sh](https://github.com/pxlsspace/Pxls/blob/e509ecf1710e0233d2626830e277a500fd7e0088/update-localizations.sh)) which can do step 2 automatically for existing localizations.

**Comment by zulujive** [comment]
Thank you! I ended up using a quite janky solution of editing the cache and using Cron to copy over the index.html file. I'll definitely update it!
