### ISSUE TITLE
Where do I type commands? (question)

### ISSUE THREAD

**Issue by SkyNetCloud** [pxlsspace/Pxls#660]
I'm very lost on where I go and type command for this software can anyone help me on locating this console thing I've very new as It few hours to get this software running to start with

**Comment by FurryMasterGithub** [comment]
in terminal

**Comment by BlankParenthesis** [comment]
You type the commands into the terminal running the main jarfile. This is obviously inconvenient, since there's no fancy input/output control, no autocomplete or other feedback, and logs will stomp all over your input and make it hard to see what you've typed: but if you type things in correctly, it will work.
